APP_NAME="MS-Admin"
SECRET_KEY="your_secret_key_here"
GRAPHQL_PATH="/graphql"
LOG_LEVEL="info"
RABBITMQ_URL="amqp://guest:guest@broker:5672/"
DATABASE_URL="mongodb://mongouser:mongopassword@mongodb:27017/?authSource=admin"
TRANSPORT_DATA_GOUV_API_URL="https://transport.data.gouv.fr/api"