services:
  mongodb:
    container_name: mongodb-hubbert
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongouser"
      MONGO_INITDB_ROOT_PASSWORD: "mongopassword"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27001:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - hubert-network

  app:
    build: .
    container_name: service_admin
    ports:
      - "8001:80"
    volumes:
      - .:/project
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --reload-dir /project"
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      hubert-network:
        aliases:
          - service-admin
volumes:
  mongodb_data:

networks:
  hubert-network:
    external: true
